<?php

namespace Drupal\hello_world\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/*
 * Configuration form definition for the salutation message
 */
class SalutationConfigurationForm extends ConfigFormBase {
  /*
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    // return a reserved space for config entry
    return ['hello_world.custom_salutation'];
  }

  /*
   * {@inheritdoc}
   */
  public function getFormId() {
  // return a unique machine name for the form
    return 'salutation_configuration_form';
  }

  /*
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('hello_world.custom_salutation');
    // assemble the render array
    $form['salutation'] = array(
      '#type' => 'textfield',
      '#title' => $this->t('Salutation'),
      '#description' => $this->t('Please provide the salutation you would like to use'),
      '#default_value' => $config->get('salutation'),
    );
    $form['colors'] = array(
      '#type' => 'radios',
      '#options' => array('blue' => $this->t('blue'), 'purple' => $this->t('purple')),
      '#title' => $this->t('Which color do you like more?'),
      '#default_value' => 'blue',
    );

    return parent::buildForm($form, $form_state);
  }
  /*
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $formState) {
    $this->config('hello_world.custom_salutation')
      ->set('salutation', $formState->getValue('salutation'))
      ->save();
    parent::submitForm($form, $formState);
  }

  // this validation is optional
  /*
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    $salutation = $form_state->getValue('salutation');
    if (strlen($salutation) > 10) {
      $form_state->setErrorByName('salutation', $this->t('this no good, too lomg!'));
    }
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }


}
